name: Full Stack CI

on:
  push:
  pull_request:

jobs:
  api-build:
    name: build api
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./api

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm install

    - name: Build API
      run: npm run build

  api-test:
    name: test api
    runs-on: ubuntu-latest
    needs: api-build 
    
    defaults:
      run:
        working-directory: ./api

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

  frontend-build:
    name: build frontend
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm install

    - name: Build frontend
      run: npm run build